[project]
name = "quiz"
authors = []
description = ""
telemetry = true
requirements = ["ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard"]

[contracts.quiz-contract]
path = "contracts/quiz-contract.clar"
depends_on = ["quiz-token"]

[contracts.quiz-token]
path = "contracts/quiz-token.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
